hook.Add("PopulateToolMenu", "PRSBOX.Hitmarkers.Settings", function() 
    spawnmenu.AddToolMenuOption("Options", "Niclude's Hitmarkers", "PRSBOXHitmarkers", "#Client", "", "", function (panel)
        panel:CheckBox( "Enable", "prsbox_hitmarkers")
		panel:NumSlider("Scale", "prsbox_hitmarkers_scale", 1, 128, 2)
		panel:NumSlider("Far point", "prsbox_hitmarkers_farpoint", 1, 512, 0)
		panel:NumSlider("Near point", "prsbox_hitmarkers_closepoint", 1, 512, 0)
		panel:NumSlider("Thickness", "prsbox_hitmarkers_thickness", 1, 128, 0)
    end)
end)